import { Command } from 'commander';
import { getPowersDir } from './config.js';
import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import chalk from 'chalk';

export const powersCommand = (program: Command) => {
    const power = program.command('power').description('Manage installed powers (tools plugins)');

    power.command('install <pkg>')
        .description('Install a power (npm package). Example: lunarstudio power install my-cool-power')
        .action((pkg) => {
            const powersDir = getPowersDir();

            // Resolve local paths correctly based on where the user ran the command
            let installTarget = pkg;
            if (pkg.startsWith('.') || pkg.startsWith('/')) {
                installTarget = path.resolve(process.cwd(), pkg);
            }

            console.log(chalk.blue(`Installing power: ${installTarget}...`));

            if (!fs.existsSync(powersDir)) {
                fs.mkdirSync(powersDir, { recursive: true });
                fs.writeFileSync(path.join(powersDir, 'package.json'), JSON.stringify({
                    name: "lunarstudio-powers",
                    description: "Auto-generated by LunarStudio",
                    dependencies: {}
                }, null, 2));
            }

            try {
                // Ensure --save is passed to persist it in package.json
                execSync(`npm install --save ${installTarget}`, { cwd: powersDir, stdio: 'inherit' });
                console.log(chalk.green(`Successfully installed ${installTarget}`));
            } catch (error) {
                console.error(chalk.red(`Failed to install ${installTarget}`));
            }
        });

    power.command('remove <pkg>')
        .description('Remove an installed power')
        .action((pkg) => {
            const powersDir = getPowersDir();
            console.log(chalk.blue(`Removing power: ${pkg}...`));

            try {
                execSync(`npm uninstall ${pkg}`, { cwd: powersDir, stdio: 'inherit' });
                console.log(chalk.green(`Successfully removed ${pkg}`));
            } catch (error) {
                console.error(chalk.red(`Failed to remove ${pkg}`));
            }
        });

    power.command('list')
        .description('List all installed powers')
        .action(() => {
            const powersDir = getPowersDir();
            const packageJsonPath = path.join(powersDir, 'package.json');

            if (!fs.existsSync(packageJsonPath)) {
                console.log(chalk.yellow('No powers installed.'));
                return;
            }

            try {
                const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
                const deps = Object.keys(pkg.dependencies || {});
                if (deps.length === 0) {
                    console.log(chalk.yellow('No powers installed.'));
                } else {
                    console.log(chalk.green('Installed Powers:'));
                    deps.forEach(dep => {
                        console.log(chalk.cyan(`  - ${dep} (${pkg.dependencies[dep]})`));
                    });
                }
            } catch (error) {
                console.error(chalk.red('Failed to read installed powers list.'));
            }
        });
};
