
import { z } from 'zod';
import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { logger } from '../src/log.js';

const DOCUMENTS_DIR = path.resolve(process.cwd(), 'dist/documents');

// Ensure directory exists
if (!fs.existsSync(DOCUMENTS_DIR)) {
    fs.mkdirSync(DOCUMENTS_DIR, { recursive: true });
}

export const documentGeneratorTool = {
    name: 'generate_document',
    description: 'Generate a high-quality PDF document from HTML content. Use for reports, summaries, invoices, etc. Returns the absolute file path.',
    schema: z.object({
        title: z.string().describe('The title of the document'),
        content: z.string().describe('The HTML body content of the document. Use semantic HTML (h1, h2, p, table, etc.)'),
        css: z.string().optional().describe('Optional CSS to style the document. Defaults to a clean, professional theme if omitted.'),
        filename: z.string().optional().describe('Desired filename (e.g., "report.pdf"). If omitted, a unique name is generated.'),
    }),
    execute: async ({ title, content, css, filename }: { title: string; content: string; css?: string; filename?: string }) => {
        try {
            logger.info(`Generating document: ${title}`);

            const safeFilename = filename ? path.basename(filename) : `${uuidv4()}.pdf`;
            const filePath = path.join(DOCUMENTS_DIR, safeFilename);

            const defaultCss = `
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap');
                body {
                    font-family: 'Inter', sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 40px;
                }
                h1 { color: #2c3e50; border-bottom: 2px solid #ecf0f1; padding-bottom: 10px; }
                h2 { color: #34495e; margin-top: 30px; }
                table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background-color: #f8f9fa; font-weight: 600; }
                tr:nth-child(even) { background-color: #f9f9f9; }
                code { background: #f4f4f4; padding: 2px 5px; border-radius: 3px; font-family: monospace; }
                blockquote { border-left: 4px solid #3498db; margin: 0; padding-left: 15px; color: #555; }
                .footer { margin-top: 50px; font-size: 0.8em; color: #7f8c8d; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
            `;

            const fullHtml = `
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <title>${title}</title>
                    <style>
                        ${defaultCss}
                        ${css || ''}
                    </style>
                </head>
                <body>
                    <h1>${title}</h1>
                    ${content}
                    <div class="footer">
                        Generated by Lunar Studio Agent • ${new Date().toLocaleDateString()}
                    </div>
                </body>
                </html>
            `;

            const browser = await puppeteer.launch({
                headless: true,
                args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.setContent(fullHtml, { waitUntil: 'networkidle0' });
            await page.pdf({
                path: filePath,
                format: 'A4',
                printBackground: true,
                margin: {
                    top: '20px',
                    right: '20px',
                    bottom: '20px',
                    left: '20px'
                }
            });

            await browser.close();
            logger.info(`Document generated at: ${filePath}`);
            return `Document created successfully: ${filePath}`;

        } catch (error: any) {
            logger.error(`Failed to generate document: ${error.message}`);
            return `Error generating document: ${error.message}`;
        }
    }
};
